# Generated by Django 4.2.21 on 2025-05-27 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tahmin90app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matchevent',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='matchevent',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='prediction',
            name='user_answer',
        ),
        migrations.RemoveField(
            model_name='prediction',
            name='username',
        ),
        migrations.AddField(
            model_name='prediction',
            name='selected_choice',
            field=models.CharField(default='A', max_length=1),
        ),
        migrations.AddField(
            model_name='prediction',
            name='user',
            field=models.CharField(default='anonymous', max_length=100),
        ),
        migrations.AddField(
            model_name='question',
            name='choices',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='question',
            name='correct_answer',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
