# Generated by Django 4.2.21 on 2025-05-28 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tahmin90app', '0002_remove_matchevent_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='choices',
            field=models.JSONField(),
        ),
    ]
