# Generated by Django 4.2.21 on 2025-05-28 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tahmin90app', '0004_predictiongroup_prediction_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictiongroup',
            name='email',
            field=models.EmailField(default='anonymous@example.com', max_length=254),
        ),
        migrations.AddField(
            model_name='predictiongroup',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='predictiongroup',
            name='user_code',
            field=models.CharField(default='anonymous', max_length=50),
        ),
    ]
