# Generated by Django 4.2.21 on 2025-05-28 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tahmin90app', '0005_predictiongroup_email_predictiongroup_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictiongroup',
            name='reward_granted',
            field=models.BooleanField(default=False, help_text='Ödül verildi mi?'),
        ),
    ]
