# Generated by Django 4.2.21 on 2025-05-28 01:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tahmin90app', '0006_predictiongroup_reward_granted'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchevent',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Maçın başlangıç zamanı'),
        ),
    ]
